### ISSUE TITLE
.net core 3.1

### ISSUE THREAD

**Issue by amitraj001** [zeoagency/aws-api-gateway-timeout-increaser#1]
Will this work for .net core 3.1
if yes then can you help me out that how will it work

**Comment by boratanrikulu** [comment]
Hi,
Yes It will be okay for any lambda. We are not familiar with .net but there is no language specific to use this repo.  
Read the documentation carefully. You need to set Proxy and Talker lambdas(these are written in this repo with Golang), also you need to set main lamda(this is your code, for you it is .net codes). The settings will set everything for you to increase timeout. You can reach to lambda's timeout limit, I guess it was 15 minutes.  
Let us know if you have any questions.
Documentation: https://github.com/zeoagency/aws-api-gateway-timeout-increaser#structure
